spring:
  profiles:
    active: local
  datasource:
    username: zotAdmin
    password: u12345u12345
    url: jdbc:mysql://zot-miner.cmry5j8qwlqu.ap-northeast-2.rds.amazonaws.com:3306/zotMiner?useUnicode=true&charaterEncoding=utf-8&autoReconnect=true&connectTimeout=3000&socketTimeout=3000
    driverClassName: com.mysql.cj.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: false
    test-on-return: false
  jpa:
    database: MYSQL
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  batch.job.enabled: false

logging.level.org:
  springframework:
    web: INFO
  hibernate: INFO
  hibernate.type.descriptor.sql.BasicBinder: TRACE

api.base.url:
  bithumb: https://api.bithumb.com

batch: 
  deleteTransaction:
    #주문히스토리 삭제 기준일. 해당 일자 이전 데이터 삭제
    deleteDate: 3
  reservationOrder:
    #10초 간의 거래체결 내역 조회
    transactionHistoryTime: 10